[package]
name = "pam_party"
version = "0.1.0"
authors = ["lucky"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-argon2 = "0.8"
pamsm = { version = "0.4", features = ["libpam"] }
